### ISSUE TITLE
Устаревшая версия SDK 1.0.8

### ISSUE THREAD

**Issue by tnt4brain** [yoomoney/cms-joomshopping#35]
В коде использована устаревшая версия SDK [1.0.8](https://github.com/yandex-money/yandex-checkout-sdk-php/tree/1.0.8), а сейчас актуальна [1.5.4](https://github.com/yandex-money/yandex-checkout-sdk-php/tree/1.5.4).

Когда планируется апгрейд?

**Comment by ostulov** [comment]
Добрый день!

На текущий момент используется одна из последних версий SDK - 1.5.2.
Обновим версию до 1.5.4 при следующем обновлении модуля для Joomshopping.

**Comment by tnt4brain** [comment]
Спасибо! Закрываю.
