### ISSUE TITLE
Joomla 3.9 нет файла XML

### ISSUE THREAD

**Issue by VicLo2020** [yoomoney/cms-joomshopping#36]
Здравствуйте
При установке на Joomla 3.9 возникает ошибка 

Warning
JInstaller: :Install: Can't find XML setup file.

Error
Path does not have a valid package.
Unable to find install package

и действительно там нет xml файла

**Comment by ostulov** [comment]
Добрый день!

Подобная ошибка возникает, если попытаться установить модуль через установку расширений для Joomla.
Данный модуль является расширением для Joomshopping, поэтому для корректной работы его необходимо устанавливать через установщик расширений Joomshopping.
![2020-02-07_21-04-59](https://user-images.githubusercontent.com/37800007/74053773-9ab74400-49ed-11ea-8233-ae3e38925819.png)

**Comment by tnt4brain** [comment]
@VicLo2020 предлагаю закрыть issue, ответ исчерпывающий.

**Comment by VicLo2020** [comment]
Спасибо за ответ
