### ISSUE TITLE
Поддержка Joomla 4.x и Joomshopping 5.x

### ISSUE THREAD

**Issue by Dem0riaN** [yoomoney/cms-joomshopping#48]
Доброго времени суток
Подскажите, ожидается ли поддержка новых версий?
Если да, то через какой промежуток времени?

**Comment by dvdxaker** [comment]
Если анализировать код, то можно сделать универсальную версию для JS 4 и JS 5. Хотелось бы уточнить по срокам и реализации?

**Comment by ostulov** [comment]
Добрый день!

Прямо сейчас прорабатываем возможность создания отдельного модуля. Пока даже примерно срок назвать не могу.

**Comment by ostulov** [comment]
В последнем релизе v2.3.0 добавлена поддержка модуля на Joomla 4.x и Joomshopping 5.x
